# Generated by Django 2.0.2 on 2018-03-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
