# Generated by Django 2.0.2 on 2018-03-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254)),
                ('pantone', models.CharField(blank=True, default='', max_length=254)),
                ('hexColorValue', models.CharField(blank=True, default='', max_length=7)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='coverPercentage',
            field=models.DecimalField(decimal_places=1, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='startingDate',
            field=models.DateField(),
        ),
    ]
