# Generated by Django 2.0.2 on 2018-03-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='rest.Color'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(to='rest.Material'),
        ),
    ]
