# Generated by Django 2.0.2 on 2018-03-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20180318_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='material',
            new_name='materials',
        ),
    ]
